"""
scripts/setup_wizard.py — interactive topology configuration for a fresh Planet Express
install. Run via the project's own venv (needs pyyaml/pydantic):

    venv/bin/python scripts/setup_wizard.py

Called from deploy.sh after the venv is set up and before the systemd units are
installed. Handles config.yaml (stacks/mounts/sudo scope) and the matching
sudoers.d grant. Secrets (LLM API key, Telegram bot token/chat id) are handled by
deploy.sh's own env-file section, not here — this script only ever touches
topology config, never credentials.

Split into a pure build_config()/generate_sudoers_snippet() (unit-tested, see
tests/test_setup_wizard.py) and an interactive main() that collects answers and
does the actual (privileged) file writes.
"""

import getpass
import glob
import os
import readline
import subprocess
import sys
from pathlib import Path

import yaml
from pydantic import ValidationError

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from config_schema import PlanetExpressConfig, SudoAllowlist  # noqa: E402


def _path_completer(text: str, state: int):
    """Registered globally (see main()) so Tab does filesystem completion instead of
    inserting a literal tab character -- a real failure mode found during this spec's
    own live verification: an uncompleted Tab silently corrupted a path prompt into
    garbage that still passed validation (it started with '/') and would have produced
    a config.yaml pointing nowhere real."""
    matches = glob.glob(os.path.expanduser(text) + "*")
    matches = [m + "/" if os.path.isdir(m) else m for m in matches]
    try:
        return matches[state]
    except IndexError:
        return None

DEFAULT_CONFIG_TARGET = "/etc/planetexpress/config.yaml"
DEFAULT_SUDOERS_TARGET = "/etc/sudoers.d/planetexpress"


def build_config(answers: dict) -> PlanetExpressConfig:
    """The whole point of building this on top of PlanetExpressConfig directly: any
    answer set that would be rejected by config.py at load time is rejected here too,
    by construction — there is no separate hand-rolled validation path to drift out of
    sync with the real schema."""
    return PlanetExpressConfig(**answers)


def generate_sudoers_snippet(run_user: str, allowlist: SudoAllowlist) -> str:
    """Render a sudoers.d NOPASSWD grant matching a SudoAllowlist exactly -- single
    source of truth with what casa_bender.py's _check_sudo_allowlist() will actually
    enforce, so the OS-level grant and the code-level allowlist can never drift apart.
    Empty allowlist -> empty string (no file worth writing)."""
    lines = []
    for grant in allowlist.units:
        cmds = ", ".join(f"/usr/bin/systemctl {action} {grant.unit}" for action in grant.actions)
        lines.append(f"{run_user} ALL=(root) NOPASSWD: {cmds}")
    for grant in allowlist.globs:
        cmds = ", ".join(f"/usr/bin/systemctl {action} {grant.glob}" for action in grant.actions)
        lines.append(f"{run_user} ALL=(root) NOPASSWD: {cmds}")
    if not lines:
        return ""
    header = (
        "# Generated by Planet Express's setup wizard (scripts/setup_wizard.py) to match\n"
        "# config.yaml's sudo_allowlist exactly. Edit config.yaml and re-run the wizard\n"
        "# rather than hand-editing this file, to keep the two in sync.\n"
    )
    return header + "\n".join(lines) + "\n"


# ── Interactive prompting helpers ─────────────────────────────────────────────


def _prompt(text: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    raw = input(f"{text}{suffix}: ").strip()
    return raw or default


# Words a user might reasonably type to mean "nothing here" instead of just pressing
# Enter -- found via this spec's own live verification, where "none" got taken
# literally and ended up as a real (garbage) list/dict entry in the written config.
_BLANK_SENTINELS = {"none", "n/a", "na", "skip"}


def _prompt_list(text: str) -> list[str]:
    raw = input(f"{text} — comma-separated names, Enter to skip: ").strip()
    if raw.lower() in _BLANK_SENTINELS:
        return []
    return [item.strip() for item in raw.split(",") if item.strip()]


def _prompt_yes_no(text: str, default: bool = False) -> bool:
    suffix = "[Y/n]" if default else "[y/N]"
    raw = input(f"{text} {suffix}: ").strip().lower()
    if not raw:
        return default
    return raw in ("y", "yes")


def _discover_stacks(stacks_root: Path) -> list[str]:
    if not stacks_root.is_dir():
        return []
    return sorted(p.parent.name for p in stacks_root.glob("*/docker-compose.yml"))


def _discover_mount_units() -> list[str]:
    try:
        result = subprocess.run(
            ["systemctl", "list-units", "--type=mount", "--all", "--no-legend", "--plain"],
            capture_output=True, text=True, timeout=10,
        )
    except (OSError, subprocess.SubprocessError):
        return []
    units = []
    for line in result.stdout.splitlines():
        parts = line.split()
        if parts and parts[0].endswith(".mount"):
            units.append(parts[0])
    return units


def _mount_where(unit: str) -> str:
    try:
        result = subprocess.run(
            ["systemctl", "show", unit, "-p", "Where", "--value"],
            capture_output=True, text=True, timeout=10,
        )
        return result.stdout.strip()
    except (OSError, subprocess.SubprocessError):
        return ""


VALID_ACTIONS = ("start", "stop", "restart")


def _prompt_actions(text: str, default: list[str]) -> list[str]:
    while True:
        raw = _prompt(text, ",".join(default))
        actions = [a.strip() for a in raw.split(",") if a.strip()]
        bad = [a for a in actions if a not in VALID_ACTIONS]
        if not bad:
            return actions
        print(f"  Invalid action(s) {bad} -- must be from {VALID_ACTIONS}. Try again.")


def _collect_sudo_allowlist() -> dict:
    if not _prompt_yes_no(
        "Let Bender restart specific systemd units or mount units during an approved "
        "remediation? (requires a matching sudoers.d grant)"
    ):
        return {"units": [], "globs": []}

    units = []
    print("Add unit grants one at a time (exact systemd unit name). Blank to stop.")
    while True:
        unit = _prompt("  Unit name")
        if not unit:
            break
        actions = _prompt_actions("  Allowed actions for this unit", ["start", "stop", "restart"])
        units.append({"unit": unit, "actions": actions})

    globs = []
    print("Add glob grants one at a time (e.g. '*.mount'). Blank to stop.")
    while True:
        glob = _prompt("  Glob pattern")
        if not glob:
            break
        actions = _prompt_actions("  Allowed actions for this glob", ["start", "stop"])
        globs.append({"glob": glob, "actions": actions})

    return {"units": units, "globs": globs}


def _collect_mounts() -> dict:
    discovered = _discover_mount_units()
    if discovered:
        print(f"Discovered mount units on this host: {', '.join(discovered)}")
    picks = _prompt_list("Which mount units should Planet Express track")
    mounts = {}
    for unit in picks:
        guess = _mount_where(unit) if unit in discovered else ""
        path = _prompt(f"  Path for {unit}", guess)
        if path:
            mounts[unit] = path
    return mounts


def _collect_stacks_root_and_forbidden() -> tuple[Path, list[str]]:
    while True:
        raw = _prompt("Path to your Docker Compose stacks directory", str(Path.home() / "stacks"))
        if any(c in raw for c in ("\t", "\n", "\r")):
            print("  That contains a tab/newline character -- if you pressed Tab expecting "
                  "path completion, it should work now; otherwise retype the path. Try again.")
            continue
        stacks_root = Path(raw).expanduser()
        if not stacks_root.is_absolute():
            print("  stacks_root must be an absolute path. Try again.")
            continue
        break
    discovered = _discover_stacks(stacks_root)
    if discovered:
        print(f"Discovered stacks: {', '.join(discovered)}")
    else:
        print(f"  No docker-compose.yml found directly under {stacks_root} -- that's fine if "
              f"you haven't created any stacks yet, or if this path is wrong.")
    forbidden = _prompt_list(
        "Any stacks Planet Express must never start/monitor/auto-update/auto-prune"
    )
    return stacks_root, forbidden


def main() -> None:
    readline.set_completer_delims(" \t\n")
    readline.parse_and_bind("tab: complete")
    readline.set_completer(_path_completer)

    print("Planet Express setup wizard — topology config\n")

    stacks_root, forbidden_stacks = _collect_stacks_root_and_forbidden()
    paused_containers = _prompt_list(
        "Any containers that are intentionally stopped right now"
    )
    mounts = _collect_mounts()
    sudo_allowlist = _collect_sudo_allowlist()

    answers = {
        "stacks_root": str(stacks_root),
        "forbidden_stacks": forbidden_stacks,
        "paused_containers": paused_containers,
        "mounts": mounts,
        "exclude_services": [],
        "sudo_allowlist": sudo_allowlist,
    }

    try:
        cfg = build_config(answers)
    except ValidationError as e:
        print(f"\nConfig failed validation:\n{e}\n")
        print("Re-run the wizard to try again.")
        sys.exit(1)

    # deploy.sh decides and exports the target path (same CASA_CONFIG convention
    # config.py itself reads) so this and the systemd units it renders always agree.
    config_target = Path(os.environ.get("CASA_CONFIG", DEFAULT_CONFIG_TARGET))
    tmp_config = Path("/tmp") / "planetexpress-config-wizard.yaml"
    tmp_config.write_text(yaml.safe_dump(cfg.model_dump(mode="json"), sort_keys=False))
    print(f"\nWriting {config_target} (requires sudo)...")
    subprocess.run(["sudo", "mkdir", "-p", str(config_target.parent)], check=True)
    subprocess.run(["sudo", "install", "-m", "644", str(tmp_config), str(config_target)], check=True)
    tmp_config.unlink()
    print(f"config.yaml written to {config_target}")

    snippet = generate_sudoers_snippet(getpass.getuser(), cfg.sudo_allowlist)
    if snippet:
        print(f"\nGenerated sudoers.d grant:\n{snippet}")
        if _prompt_yes_no(f"Install this to {DEFAULT_SUDOERS_TARGET}?", default=True):
            tmp_sudoers = Path("/tmp") / "planetexpress-sudoers-wizard"
            tmp_sudoers.write_text(snippet)
            check = subprocess.run(["visudo", "-c", "-f", str(tmp_sudoers)], capture_output=True, text=True)
            if check.returncode != 0:
                print(f"visudo rejected the generated snippet, not installing:\n{check.stderr}")
                tmp_sudoers.unlink()
                sys.exit(1)
            subprocess.run(["sudo", "install", "-m", "440", str(tmp_sudoers), DEFAULT_SUDOERS_TARGET], check=True)
            tmp_sudoers.unlink()
            print(f"Sudoers grant installed to {DEFAULT_SUDOERS_TARGET}")
        else:
            print("Skipped -- Bender's sudo_allowlist actions will be rejected by the OS "
                  "until you grant them at the OS level yourself.")
    else:
        print("\nNo sudo_allowlist declared -- Bender won't run any sudo-scoped commands.")

    print(f"\nDone. config.yaml -> {config_target}")


if __name__ == "__main__":
    main()
